apiVersion: v1
kind: Pod
metadata:
  name: JenkinsCI
spec:
  nodeSelector:
    docker: "true"
  containers:
    - image: gradle:latest
      name: gradle1
      command:
        - sleep
      args:
        - 99d
      resources:
        requests:
          cpu: "50m"
          memory: "256Mi"
        limits:
          cpu: "200m"
          memory: "1024Mi"

    - image: gradle:latest
      name: gradle2
      command:
        - sleep
      args:
        - 99d
      resources:
        requests:
          cpu: "50m"
          memory: "256Mi"
        limits:
          cpu: "200m"
          memory: "1024Mi"

    - image: gradle:latest
      name: gradle3
      command:
        - sleep
      args:
        - 99d
      resources:
        requests:
          cpu: "50m"
          memory: "256Mi"
        limits:
          cpu: "200m"
          memory: "1024Mi"    

    - image: docker:latest
      name: docker
      command:
        - sleep
      args:
        - 99d
      volumeMounts:
        - mountPath: /var/run/docker.sock
          name: containerd-sock
      resources:
        requests:
          cpu: "50m"
          memory: "256Mi"
        limits:
          cpu: "200m"
          memory: "1024Mi"

  volumes:
    - name: containerd-sock
      hostPath:
        path: /var/run/docker.sock
        type: Socket