apiVersion: v1
kind: Pod
metadata:
  name: JenkinsCI
spec:
  nodeSelector:
    docker: "true"
  containers:
    - image: gradle:latest
      name: gradle
      command:
        - sleep
      args:
        - 99d
      resources:
        requests:
          memory: '256Mi'
          cpu: '500m'
        limits:
          memory: '4Gi'
          cpu: 4

    - image: docker:latest
      name: docker
      command:
        - sleep
      args:
        - 99d
      volumeMounts:
        - mountPath: /var/run/docker.sock
          name: containerd-sock
      resources:
        requests:
          memory: '256Mi'
          cpu: '500m'
        limits:
          memory: '4Gi'
          cpu: 4

  volumes:
    - name: containerd-sock
      hostPath:
        path: /var/run/docker.sock
        type: Socket