apiVersion: v1
kind: Pod
metadata:
  name: JenkinsCI
spec:
  nodeSelector:
    docker: "true"
  containers:
    - image: gradle:latest
      name: gradle
      command:
        - sleep
      args:
        - 99d

    - image: docker:latest
      name: docker
      command:
        - sleep
      args:
        - 99d
      volumeMounts:
        - mountPath: /var/run/docker.sock
          name: containerd-sock

  volumes:
    - name: containerd-sock
      hostPath:
        path: /var/run/docker.sock
        type: Socket