apiVersion: v1
kind: Pod
metadata:
  name: JenkinsCI
spec:
  nodeSelector:
    docker: "true"
  containers:
    - image: gradle:7.2.0-jdk11-alpine
      name: gradle1
      command:
        - sleep
      args:
        - 99d
      resources:
        requests:
          cpu: "250m"
          memory: "256Mi"
        limits:
          cpu: 1
          memory: "2048Mi"

    - image: gradle:7.2.0-jdk11-alpine
      name: gradle2
      command:
        - sleep
      args:
        - 99d
      resources:
        requests:
          cpu: "250m"
          memory: "256Mi"
        limits:
          cpu: 1
          memory: "2048Mi"

    - image: docker:latest
      name: docker
      command:
        - sleep
      args:
        - 99d
      volumeMounts:
        - mountPath: /var/run/docker.sock
          name: containerd-sock
      resources:
        requests:
          cpu: "250m"
          memory: "256Mi"
        limits:
          cpu: 1
          memory: "1024Mi"

  volumes:
    - name: containerd-sock
      hostPath:
        path: /var/run/docker.sock
        type: Socket