apiVersion: v1
kind: Pod
metadata:
  name: jenkins-ci-cd
spec:
  containers:
    - image: gradle:7.2.0-jdk11-alpine
      name: gradle
      command:
        - sleep
      args:
        - 99d
      resources:
        limits:
          cpu: 1
          memory: "1024Mi"

    - image: docker:latest
      name: docker
      command:
        - sleep
      args:
        - 99d
      volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
      resources:
        limits:
          cpu: 1
          memory: "1024Mi"

    - image: lachlanevenson/k8s-kubectl:v1.18.3
      name: kubectl
      command:
        - cat
      tty: true
      resources:
        limits:
          cpu: "500m"
          memory: "128Mi"
      volumeMounts:
        - mountPath: /root/.kube/config
          name: k3s-config

  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
        type: Socket
        
    - name: k3s-config
      hostPath:
        path: ~/projects/k8s/k3s/config
        type: File