apiVersion: v1
kind: Pod
metadata:
  name: jenkins-ci-cd
spec:
  containers:
    - image: gradle:7.2.0-jdk11-alpine
      name: gradle
      command:
        - sleep
      args:
        - 99d
      resources:
        limits:
          cpu: 1
          memory: "1024Mi"

    - image: docker:latest
      name: docker
      command:
        - sleep
      args:
        - 99d
      volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
      resources:
        limits:
          cpu: 1
          memory: "1024Mi"

    - image: rancher/kubectl:v1.22.2
      name: kubectl
      command:
        - sleep
      args:
        - 99d
      resources:
        limits:
          cpu: "500m"
          memory: "128Mi"

  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
        type: Socket